/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    readMatrices
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_Main_readMatrices
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Main
 * Method:    multiply
 * Signature: (Ljava/lang/String;)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_Main_multiply__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Main
 * Method:    multiply
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_multiply__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Main
 * Method:    multiply
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_Main_multiply___3_3D_3_3D
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
